---
- name: 'Python 3 playbook'
  hosts: default
  vars: 
    ansible_python_interpreter: "/usr/bin/python2.7"

  tasks:
    - name: Installing Python 3
      yum: 
        name: python3
        state: present
        update_cache: yes 
      become: true  
  