---
- name: 'Font Config playbook'
  hosts: default
  vars: 
    ansible_python_interpreter: "/usr/bin/python2.7"

  tasks:
    - name: Installing Font config
      yum: 
        name: fontconfig
        state: present
        update_cache: yes 
      become: true  
  